"""add mechanism downloads table - fixed

Revision ID: 8079dc4a158a
Revises: 5bc3762b61da
Create Date: 2025-07-06 21:53:38.665845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8079dc4a158a'
down_revision: Union[str, None] = '5bc3762b61da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanism_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanism_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanisms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanism_downloads_id'), 'mechanism_downloads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanism_downloads_id'), table_name='mechanism_downloads')
    op.drop_table('mechanism_downloads')
    # ### end Alembic commands ###
