"""add mechanism view model

Revision ID: 2023052501
Revises: ab1384850060
Create Date: 2025-05-10 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023052501'
down_revision = 'ab1384850060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanism_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanism_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanisms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanism_views_id'), 'mechanism_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanism_views_id'), table_name='mechanism_views')
    op.drop_table('mechanism_views')
    # ### end Alembic commands ###
