"""add is_admin field to users table

Revision ID: fff8e3cb87f3
Revises: 8079dc4a158a
Create Date: 2025-07-26 22:54:46.241697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff8e3cb87f3'
down_revision: Union[str, None] = '8079dc4a158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # まずnullableでカラムを追加
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # 既存のユーザーにデフォルト値を設定
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    # その後NOT NULL制約を追加
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
